<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-I10571T" failures="2" tests="3" name="Default test(failed)" time="0.082" errors="0" timestamp="2022-02-17T13:59:14 IST">
  <testcase classname="SamplePackage.SampleClass1" name="method2" time="0.012">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at SamplePackage.SampleClass1.method2(SampleClass1.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method2 -->
  <testcase classname="SamplePackage.SampleClass1" name="method4" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at SamplePackage.SampleClass1.method4(SampleClass1.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- method4 -->
  <testcase classname="SamplePackage.SampleClass1" name="method5" time="0.0">
    <skipped/>
  </testcase> <!-- method5 -->
  <testcase classname="SamplePackage.SampleClass1" name="method3" time="0.0">
    <ignored/>
  </testcase> <!-- method3 -->
  <testcase classname="SamplePackage.SampleClass1" name="method1" time="0.0">
    <ignored/>
  </testcase> <!-- method1 -->
</testsuite> <!-- Default test(failed) -->
